### PR TITLE
Add support for TEMPerHumM12V1.2 and TEMPerHumM12V1.3

### PR DESCRIPTION
**Pull request by normanr**

### CODE REVIEW

**Comment by mwerezak** [comment]
Just tried it with a TEMPerHUM12V1.3, the example programs (read-all and read-repeat) both work.

**Comment by mwerezak** [comment]
Fixes #38

**Comment by nudomarinero** [comment]
I can confirm that this PR makes TEMPerHUM12V1.3 devices work.

**Comment by mpatalberta** [comment]
pcsensor has introduced yet another usb system thay gives temperature and humidity. I have the code function however the values are wrong. I am pretty sure I am missing the conversion from counts to to temperature and relative humidity.

**Comment by endolith** [comment]
Why hasn't this been merged?  

Also it needs to be added to the DEVICES file

**Comment by mpatalberta** [comment]
No idea what you are are talking about.

**Comment by mwerezak** [comment]
@normanr  I think this repo is dead. If you target your PR to https://github.com/mwerezak/TEMPered I will try to merge it.

**Comment by normanr** [comment]
Replaced by https://github.com/mwerezak/TEMPered/pull/4

**Pull request closed without merging**
